url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Michael A. Paarlberg" # the name of your site, e.g. ACME Corp.
description: "Assistant Professor of Political Science"
university: "Virginia Commonwealth University"

logging:
  level: debug
