url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Michael Ahn Paarlberg" # the name of your site, e.g. ACME Corp.
description: "Associate Professor of Political Science at Virginia Commonwealth University"
university:

logging:
  level: debug

collections:
  pages:
    output: true

google_analytics: G-Q6176YEML2
