menu:
- {name: 'teaching', url: '/teaching'}
- {name: 'publications', url: '/publications'}
- {name: 'research', url: '/research'}
- {name: 'cv', url: '/cv'}
- {name: 'journalism', url: '/journalism'}