menu:
  - { name: "Home", url: "#home" }
  - { name: "Scholarship", url: "#scholarship" }
  - { name: "Op-eds", url: "#opeds" }
  - { name: "Media Coverage", url: "#media-coverage" }
  - { name: "Teaching", url: "#teaching" }
