menu:
- {name: 'About', url: '/home'}
- {name: 'Media', url: '/journalism'}
- {name: 'Teaching', url: '/teaching'}
- {name: 'Publications', url: '/publications'}
- {name: 'Research', url: '/research'}
- {name: "Profile", url: "/profile"}