menu:
  - { name: "Home", url: "/" }
  - { name: "Media Coverage", url: "/media-coverage" }
  - { name: "Teaching", url: "/teaching" }
  - { name: "Publications", url: "/publications" }
  - { name: "Research", url: "/research" }
